const superHeroes = [
  {
    name: "IRON MAN",
    height: 175,
    weight: 80,
    photo: "im.jpg",
    company: "Marvel",
    gender: "male",
  },
  {
    name: "HULK",
    height: 250,
    weight: 300,
    photo: "hulk.jpg",
    company: "Marvel",
    gender: "male",
  },
  {
    name: "Batman",
    height: 180,
    weight: 90,
    photo: "batman.jpg",
    company: "DC",
    gender: "male",
  },
  {
    name: "Super Woman",
    height: 175,
    weight: 60,
    photo: "sw.jpg",
    company: "DC",
    gender: "female",
  },
  {
    name: "Super Man",
    height: 182,
    weight: 85,
    photo: "sm.jpg",
    company: "DC",
    gender: "male",
  },
  {
    name: "Penguin",
    height: 150,
    weight: 65,
    photo: "penguin.jpg",
    company: "DC",
    gender: "male",
  },
  {
    name: "Cat Woman",
    height: 168,
    weight: 55,
    photo: "catwoman.jpg",
    company: "DC",
    gender: "female",
  },
  {
    name: "Rorschach",
    height: 178,
    weight: 75,
    photo: "rorschach.jpg",
    company: "DC",
    gender: "male",
  },
];
export { superHeroes };
